postgres:
  host: 127.0.0.1
  post: 5432
  dbname: iris_community
  user: postgres
  password: admino0o0oo0
  sslmode: disable
redis:
  url: localhost:6379
  actcTimeout: 7200 #激活码过期时间（秒，默认两小时）
  rescTimeout: 7200 #重置密码过期时间（秒，默认两小时）
  vercTimeOut: 600 #验证码过期时间（秒,默认10分钟）
server: 0.0.0.0:8080
mail:
  host: smtp.ym.163.com
  port: 25
  username: vincent@bianjie.ai
  password: a345407031
staticPath: D:\test\static  #静态文件路径
aliYun:
  accessKeyId: LTAIXvuWGlEeJmz5
  accessKeySecret: 1NUb2UtYjyTOYeX8u9TaN0tCUSNJrx
  oss:
    endpoint: http://oss-cn-shanghai.aliyuncs.com
    bucket: bianjie-default
  sls:
    endpoint: https://sts.aliyuncs.com
    arn: acs:ram::1768586477174862:role/aliyuncloudmonitordefaultrole