postgres:
  host: 127.0.0.1
  post: 5432
  dbname: iris_community
  user: postgres
  password: admino0o0oo0
  sslmode: disable
server: 0.0.0.0:80
mail:
  host: smtp.163.com
  port: 25
  username: XXX@163.com
  password: XXX
staticPath: D:\test\static  #静态文件路径
aliYun:
  endpoint:
  accessKeyId:
  accessKeySecret:
  bucket: