postgres:
  host: 192.168.150.242
  post: 5432
  dbname: iris_community
  user: postgres
  password: admino0o0oo0
  sslmode: disable
server: 0.0.0.0:8080
mail:
  host: smtp.163.com
  port: 25
  username: XXX@163.com
  password: XXX
staticPath: D:\test\static  #静态文件路径
aliYun:
  accessKeyId: LTAIXvuWGlEeJmz5
  accessKeySecret: 1NUb2UtYjyTOYeX8u9TaN0tCUSNJrx
  oss:
    endpoint: http://oss-cn-shanghai.aliyuncs.com
    bucket: bianjie-default
  sls:
    endpoint: https://sts.aliyuncs.com
    arn: acs:ram::1768586477174862:role/aliyuncloudmonitordefaultrole