postgres:
  host: 127.0.0.1
  post: 5432
  dbname: iris_community
  user: postgres
  password: admino0o0oo0
  sslmode: disable
server: 0.0.0.0:8080
mail:
  host: smtp.ym.163.com
  port: 25
  username: vincent@bianjie.ai
  password: XXX
staticPath: D:\test\static  #静态文件路径
aliYun:
  accessKeyId:
  accessKeySecret:
  oss:
    endpoint: http://oss-cn-shanghai.aliyuncs.com
    bucket: bianjie-default
  sts:
    endpoint: https://sts.aliyuncs.com
    arn: acs:ram::1768586477174862:role/aliyunosswriteandreadrole
    version: 2015-04-01